# Generated by Django 4.2.5 on 2023-09-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_user_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
