# Generated by Django 4.2.5 on 2023-09-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
