# Generated by Django 4.2.5 on 2023-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título:')),
                ('dt_criacao', models.DateField(auto_now_add=True)),
                ('dt_prevista', models.DateField(verbose_name='Data de Entrega:')),
                ('dt_conclusao', models.DateField(null=True)),
            ],
        ),
    ]
