# Generated by Django 4.2.5 on 2023-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_tarefa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email: '),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome completo:'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(default='', max_length=80, verbose_name='Usuário:'),
        ),
    ]
