# Generated by Django 4.2.5 on 2023-10-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_alter_user_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_nickname',
        ),
    ]
