# Generated by Django 4.2.5 on 2023-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holyday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(default='', max_length=255)),
                ('holiday_date', models.DateField(default='')),
                ('holiday_type', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
