# Generated by Django 4.2.5 on 2023-10-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('date', models.DateField(default='')),
                ('type', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Holyday',
        ),
    ]
